### ISSUE TITLE
Testing utilities for JS/TS services

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/sdk-typescript#101]
In order to provide a good dev-ex, it would be great if we provided our users some testing utilities to easily test their services via unit and integration tests.

**Comment by slinkydeveloper** [comment]
In the Java SDK we have some testing utilities based on testcontainers. This is a sample usage: https://github.com/restatedev/sdk-java/blob/main/sdk-test/src/test/java/dev/restate/sdk/testing/CounterTest.java

We could replicate the same experience in the ts sdk using testcontainers-node

**Comment by tillrohrmann** [comment]
Would it possible to directly use test-containers w/o a wrapping framework? If so, could it become an example?

**Comment by tillrohrmann** [comment]
An idea that came up was to publish our testcontainer image as an [official testcontainers module](https://testcontainers.com/modules/?_gl=1*fsk3i*_up*MQ..*_ga*MjE0MjQ3NTIyOS4xNzAyMzgxNjQw*_ga_22TYV8FBPD*MTcwMjM4MTYzNy4xLjEuMTcwMjM4MTY1My4wLjAuMA..).

**Comment by slinkydeveloper** [comment]
Some experiments: https://github.com/restatedev/node-template-generator/pull/19

**Comment by slinkydeveloper** [comment]
Solved by adding an example.
