### ISSUE TITLE
Make RestateContext.oneWayCall and .delayedCall synchronous methods

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/sdk-typescript#111]
Given that `RestateContext.oneWayCall` and `RestateContext.delayedCall` don't return any values, it would be great if we could get rid of the `Promise` in the return type and instead make these methods synchronous. If somethings fails on the way to sending the respective journal entry, we should be able to directly fail. Moreover, it makes the interface clearer for our users.

**Comment by slinkydeveloper** [comment]
This is now irrelevant
