### ISSUE TITLE
Awakeable promise should only be created when awaiting it

### ISSUE THREAD

**Issue by gvdongen** [restatedev/sdk-typescript#123]
If you have this code snippet:
```
const { id, promise } = ctx.awakeable<number[]>();

await ctx.sideEffect(async () => {
   await sendTheIdSomewhere(id);
});

const sortedNumbers: number[] = await promise;
```
and there is a suspension (for whatever reason) in between the creation of the awakeable and the side effect to send the ID to an external party. then the invocation might stall forever. Because if this awakeable promise is the only suspension index, then the runtime will only reinvoke the service after receiving the completeAwakeableMessage for this awakeable. But if the ID has not been sent to the external party yet, then the function will never be woken up.

**Comment by slinkydeveloper** [comment]
we don't need this anymore
