### ISSUE TITLE
Implement CANCELLING state

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/sdk-typescript#192]
Implement the CANCELLING state as described here: https://docs.google.com/document/d/14s7D6KP1IKNS1K3OrVbZNKGNei9TO_-9Sk0YC5mpht8/edit#heading=h.d6pdcztkz6gj

**Comment by slinkydeveloper** [comment]
This needs some refinements of how this feature will look like in the TS SDK.

**Comment by slinkydeveloper** [comment]
The `CancelledError` has been superseded by by https://github.com/restatedev/sdk-typescript/issues/94

**Comment by tillrohrmann** [comment]
This issue is not needed for the current scope of the cancellation feature. Please re-open once we tackle the later steps.
