### ISSUE TITLE
Side effects should wait for other entries acks

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/sdk-typescript#193]
Send REQUIRES_ACK flag for all the entries, and wait for the ack of those in side effects.

See https://docs.google.com/document/d/14s7D6KP1IKNS1K3OrVbZNKGNei9TO_-9Sk0YC5mpht8/edit#heading=h.hooeo8f4d03z for more details.

**Comment by tillrohrmann** [comment]
Closing because it is not needed atm.

**Comment by tillrohrmann** [comment]
Closing because it is not needed atm.
