### ISSUE TITLE
Provide a way to expose typed ingress clients

### ISSUE THREAD

**Issue by jackkleeman** [restatedev/sdk-typescript#199]
It would be great if I can import the type for a service/router, combine it with a restate ingress URL, and invoke the service via the ingress in a typed way

**Comment by tillrohrmann** [comment]
Some open question to figure out

```[tasklist]
### Tasks
- [ ] What client library to use for the transport?
- [ ] Whether keeping heuristic for keyed vs. unkeyed service detection
```

**Comment by tillrohrmann** [comment]
Ideally similar to the tRPC client.

**Comment by jackkleeman** [comment]
https://trpc.io/docs/client/vanilla/setup

**Comment by tillrohrmann** [comment]
We should also check that our documentation is up to date with how to invoke Restate services from externally.

**Comment by slinkydeveloper** [comment]
Solved.
