### ISSUE TITLE
Rename method to create Lambda Handler

### ISSUE THREAD

**Issue by gvdongen** [restatedev/sdk-typescript#229]
To create a Lambda handler we do:
`export const handler = restate
  .createLambdaApiGatewayHandler()
  .bindRouter(myServiceApi.path, serviceRouter)
  .bindKeyedRouter(myKeyedServiceApi.path, keyedServiceRouter)
  .handle();`
  
  But we do not require to go over API Gateway anymore so we can rename `createLambdaApiGatewayHandler` to `createLambdaHandler`

**Comment by slinkydeveloper** [comment]
We also need to update the examples in the https://github.com/restatedev/examples repo.
