### ISSUE TITLE
Can we unify RESTATE_DEBUG_LOGGING and RESTATE_LOGGING?

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/sdk-typescript#332]
While testing the TS SDK I noticed that we have two env variables for configuring the logging: `RESTATE_DEBUG_LOGGING` and `RESTATE_LOGGING`. It seems that we have two mechanisms for emitting log messages. In our documentation we have only documented the former. Can we unify both to make it simpler for our users to conifgure logging?

**Comment by slinkydeveloper** [comment]
Fixed by https://github.com/restatedev/sdk-typescript/commit/58d9a2ac6d67aa1ed3bdeaa92b2cbecb4785eeee
