### ISSUE TITLE
Deno 2.0 breaks request identity validation

### ISSUE THREAD

**Issue by jackkleeman** [restatedev/sdk-typescript#436]
It appears that Deno 2.0 now sets the process global and pretends to be node, which means we won't use webcrypto in deno. Sadly their non webcrypto node polyfill doesnt support ed25519, even though the webcrypto does. This may not matter if we are moving to the shared core

**Comment by slinkydeveloper** [comment]
@jackkleeman currently we're not using the shared core for the request identity, shall we do it?
