### ISSUE TITLE
Include ctx.key in `ctx.console.*` output

### ISSUE THREAD

**Issue by dimfeld** [restatedev/sdk-typescript#453]
Currently the output from `ctx.console.log` and similar includes the service name, the invocation ID, and the timestamp. It would be very useful IMO if it included `ctx.key` for objects and workflows as well so we don't have to manually include it in every call. Any thoughts on this?

**Comment by tillrohrmann** [comment]
Thanks for the suggestion @dimfeld. I think this is a good idea for improving Restate's logging capabilities :-) @slinkydeveloper is the required information already present so that we can add it to log statements?

**Comment by dimfeld** [comment]
Looks like `input.key` can be passed into LoggerContext here to facilitate this:

https://github.com/restatedev/sdk-typescript/blob/443630750266be4402215263a971ef8eed313f3c/packages/restate-sdk/src/endpoint/handlers/generic.ts#L279-L285

since it's in ContextImpl which is created a few lines down https://github.com/restatedev/sdk-typescript/blob/443630750266be4402215263a971ef8eed313f3c/packages/restate-sdk/src/endpoint/handlers/generic.ts#L301-L304

I did notice that the ContextImpl class uses an accessor for key though, so it may be wise to reuse some of that code albeit without throwing an error when `key` doesn't apply.

https://github.com/restatedev/sdk-typescript/blob/443630750266be4402215263a971ef8eed313f3c/packages/restate-sdk/src/context_impl.ts#L122-L132

**Comment by PfisterFactor** [comment]
Piggy-backing off this issue - it would be nice in general to have access to the workflow/virtual object's state from the logger as well as it's key.

**Comment by slinkydeveloper** [comment]
I added it in #455. this is the sample output:

```
[restate] [2024-10-30T14:30:32.185Z] INFO:  Listening on 9080...
[restate] [2024-10-30T14:30:32.187Z] WARN:  Accepting requests without validating request signatures; handler access must be restricted
[restate] [counter/my-todo/current][inv_1d5kQ1mT8mq25dhBiJt196gS7bmQw0oMsV][2024-10-30T14:30:33.289Z] INFO:  my log line
```
