### ISSUE TITLE
Unexpected logging changes

### ISSUE THREAD

**Issue by mupperton** [restatedev/sdk-typescript#469]
Using SDK 1.3.3, on a replay you would get a log of `"Resuming (replaying) function."` - This no longer appears on `0.0.0-SNAPSHOT-20241218144711`

Also on `0.0.0-SNAPSHOT-20241218144711` the `"Function completed with an error.\n"` logs used have `params.source` = "JOURNAL" but now they are "USER"

For context I am using the custom logger callback

**Comment by jackkleeman** [comment]
i am working on a fix @igalshilman
