### ISSUE TITLE
Restate dist size is 1.3MB

### ISSUE THREAD

**Issue by igalshilman** [restatedev/sdk-typescript#51]
Looking at the `dist/` size we can see that `./generated/google/` takes 600k

```bash
[/sdk-typescript/dist]$ du -h 
72K	./types
40K	./io
248K	./generated/proto
24K	./generated/dev/restate
28K	./generated/dev
596K	./generated/google/protobuf
600K	./generated/google
880K	./generated
76K	./server
68K	./connection
56K	./utils
1,3M	.

```

These 600K are used only for the discovery endpoint. Let us investigate how the discovery can be made a bit more lightweight.
For example one can replace the manual `FileDescriptorSet` creation, with the compile time bundling of the file descriptor set. This can be built via `buf` and included in the artifact when running `npm run proto`.
This would only make sense if the generated binary `file descriptor set` is smaller in size than 600kb.
Removing that gets us to `700kb` bundle size, (50%).

Another way would be to incorporate `esbuild` to generate minified `.js` files, at least for the big ones we have.

**Comment by slinkydeveloper** [comment]
This is irrelevant now.
