### ISSUE TITLE
State in unkeyed services is confusing 

### ISSUE THREAD

**Issue by StephanEwen** [restatedev/sdk-typescript#63]
State can be used in unkeyed services like in keyed services. It will stay around after the service invocation is over.
But because the internally-used key was transient, the state will not be addressable again. Just dead state, taking up space in the runtime.

Maybe state is just useless in unkeyed services. But also, maybe it is not: For a very long running service (think periodic billing workflow), setting state could be helpful for external visibility to the workflow: queries from the CLI, CDC consumers, ...

I would propose to do one of the following things:

1. Either forbid use of state in unkeyed services all together
2. Or, if we believe state is helpful in unkeyed services, auto-clear it when the invocation is done.
3. Or, if we want to combine both, we could have `setTransientState()`, which works in both keyed and unkeyed services, and auto-clears at the and of the handler invocation.

It seems all this might even be doable SDK side.

**Comment by slinkydeveloper** [comment]
Solved.
